
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: graf-data-dir-pvc
  namespace: {{ .Values.application.namespace }}

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

