apiVersion: apps/v1

apiVersion: v1
kind: Service

metadata:
  name: grafana
  namespace: {{ .Values.application.namespace }}

spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
    
