
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.application.namespace }}

spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
   - port: 9090
     targetPort: 9090
     nodePort: 31000
